### ISSUE TITLE
Not an issue, but a suggestion

### ISSUE THREAD

**Issue by OrionRandD** [erikdubois/arcolinux-nemesis#1]
Hi, Erik,
Do you know this project?
I am trying to figure out how to make it work with pywal/wal
Seems very interesting.
https://github.com/themix-project/oomox
Although I do not use ArchLinux and neither I3-wm.
Some time ago I was a heavy I3 user, but have migrated to Stumpwm.
https://archive.org/details/TheStumpWMExperience
https://github.com/stumpwm/stumpwm
Could you also make a video tuto on how to match firefox skin with pywal/wal?
Thx a lot for you work and sharing knowledge.

**Comment by erikdubois** [comment]
oomox is installed via yay.
The other suggestions is not up my alley.

**Comment by OrionRandD** [comment]
Thx for clarifying
