### ISSUE TITLE
arconet-xfce-24.07-02 and arconet-xfce-nemesis-24.07-02 are in conflict

### ISSUE THREAD

**Issue by sgremm** [erikdubois/arcolinux-nemesis#13]
I am tried to update after half year. The error message above apears. Both package is uninstalled
The Debug message is:

Fehler: Nicht auflösbare Paketkonflikte gefunden
Fehler: Vorgang konnte nicht vorbereitet werden (In Konflikt stehende Abhängigkeiten)
:: arconet-xfce-24.07-02 and arconet-xfce-nemesis-24.07-02 are in conflict

Sorry is in german

**Comment by erikdubois** [comment]
it should conflict
it is the same...do not use nemesis - that is just for testing

**Comment by sgremm** [comment]
How i disable nemesis. i have comment in pacman.conf but the conflict ist not gone

**Comment by erikdubois** [comment]
you can not have both...
should not be in pacman.conf - ever

sudo pacman -R ...nemesis and install the correct one

**Comment by sgremm** [comment]
I have no nemesis entry in pacman.conf but the error is still there

debug: looking for conflicts
debug: check targets vs targets
debug: check targets vs targets
debug: package arconet-xfce conflicts with arconet-xfce-nemesis (by arconet-xfce-nemesis)
debug: package arconet-xfce-nemesis conflicts with arconet-xfce (by arconet-xfce)
debug: conflicting packages in the sync list: 'arconet-xfce' <-> 'arconet-xfce-nemesis'
Fehler: Nicht auflösbare Paketkonflikte gefunden
Fehler: Vorgang konnte nicht vorbereitet werden (In Konflikt stehende Abhängigkeiten)
:: arconet-xfce-24.07-02 and arconet-xfce-nemesis-24.07-02 are in conflict

**Comment by erikdubois** [comment]
come to discord
here I can not help

**Comment by sgremm** [comment]
i have no discord, sorry,  no nemesis packet installed , i have no idea, i will only update the system.

**Comment by erikdubois** [comment]
I think I figured it out
type 'update' again

**Comment by sgremm** [comment]
why are conflict with packages that not installed

**Comment by erikdubois** [comment]
solved now
