### ISSUE TITLE
Invalid signature 

### ISSUE THREAD

**Issue by ankitgahlyan** [erikdubois/arcolinux-nemesis#7]
error: nomacs: signature from "Erik Dubois <erik.dubois@gmail.com>" is invalid
:: File /var/cache/pacman/pkg/nomacs-1:3.17.2287-1-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] 

how to resolve it?

**Comment by erikdubois** [comment]
type 'fixkey' in a terminal
this is not the way to contact me
telegram and discord is the way
